Repository Kenttrann2302/StudyHub-Backend, pull requests merged in 2023-05, with the labels that each got.

#21 Finish Google-OAuth2.0 Implementation
  .gitignore
  Test_RestAPI/requirements.txt
  app.py
  database/users_models.py
  get_env.py
  login.py
  migrations/versions/a783fe0a8b8d_change_users_model.py
  requirements.old.txt
  requirements.txt
  study_preferences.py
Labels: feature

#22 Dockerize backend development environments
  Dockerfile
  Pipfile
  Pipfile.lock
  Test_RestAPI/testLogin.py
  Test_RestAPI/testProfile.py
  Test_RestAPI/testRegistration.py
  Twilio/templates/twilio_delete_template.html
  Twilio/templates/twilio_post_template.html
  Twilio/templates/twilio_update_template.html
  app.py
  database/users_models.py
  docker-compose.yml
  get_env.py
  helper_functions/registerformValidation.py
  login.py
  migrations/versions/1ce31aa05141_change_cascade_deletion.py
  migrations/versions/c6d7fefc6a0a_changing_database.py
  register.py
  requirements.old.txt
  requirements.txt
  user_profile.py
Labels: task

#24 Availability Schedule API
  app.py
  availability_schedule.py
  database/users_models.py
  migrations/versions/50700a20abe3_change_db.py
  migrations/versions/788438e53731_change_db.py
  migrations/versions/8894e39184ff_change_db.py
  register.py
  study_preferences.py
Labels: feature, help wanted, question
